name: 'GitHub Action for Firebase'
author: 'Dhruvin Rakholiya'
description: 'Wraps the firebase-tools CLI to enable common commands.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'docker://dhruvin3346/firebase_action_version770:latest'