name: Build and Deploy

on: 
  push: 
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 8.x
      - name: Install Dependencies
        run: npm install
      - name: Create project build
        run: npm run build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
