name: Build

on:
  push:
    branches:
      - firebase_version

jobs:
  build:
    name: docker build & push
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v2
      - name: docker/build-push
        uses: docker/build-push-action@v1
        with:
          username: dhruvinrakholiya
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dhruvinrakholiya/demo-ci-cd
          branches: firebase_version