name: Build and Deploy

on: 
  push: 
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
        with:
          node-version: 8.17.0
      - name: Install Dependencies
        run: npm install
      - name: Deploy to firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
