name: Build and Deploy

on: 
  push: 
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change Path and Install dependencies
      run: cd functions && npm install
    - name: Deploy to Firebase
      uses: dhruvinrakholiya/firebase-action-version-7.7.0@firebase_version
      with:
        args: deploy --only functions,hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
