name: Build and Deploy

on: 
  push: 
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change Path
      run: cd functions
    - name: Install Dependencies
      run: npm install  
    - name: Deploy to firebase
    - uses: chrissank/deploy-firebase-functions@1.0.0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TARGET: default  
#       uses: doonstore/firebase-deploy@v1
#       with:
#         params: --only functions
#       uses: w9jds/firebase-action@master
# #
#       with:
#         args: deploy --only functions,hosting
#       env:
#         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#         FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
