name: Build and Deploy

on: 
  push: 
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: Deploy to firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
