name: Build and Deploy

on: 
  push: 
    branches: [ master ]
    
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Change Path
      run: cd functions
    - name: Install Dependencies
      run: npm install  
    - name: Deploy to firebase
#       uses: doonstore/firebase-deploy@v1
#       with:
#         params: --only functions
    - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_CI_CD_56630 }}'
          channelId: live
          projectId: fir-ci-cd-56630
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
